#!/usr/bin/env bash
# Supersitions
i=1
while [ "$i" -le 20 ]
	echo "$i"
	case $i in
	    4)
            echo "bad luck from China"
            ;;
            9)
            echo "bad luck from Japan"
            ;;
            17)
            echo "bad luck from Italy"
            ;;
         esac

         i=$((i + 1))
done
i=$i
