#!/usr/bin/env/ bash
# Displaying Best School
file_h="school"

if [ -e "$file_h" ]
then

	echo "school file exists"
	if [ -s "$file_h" ]
	then
            echo "school file is not empty"
	else
            echo "school file is empty"
	fi

	if [ -f "$file_h" ]
	then
	    echo "school is a regular file"
	fi
else
:wq

fi
